---
title: 'Homework: R Markdown and Leaflet'
author: "Espen Svendsen"
date: "21 12 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Immigration stats to Norway

The numbers are provided by the gouvernent agency [Statistics Norway](http://www.ssb.no/innvandring-og-innvandrere/nokkeltall/innvandring-og-innvandrere#omssb-hovedmeny)

```{r leaflet_map, echo=FALSE, warning=FALSE, message=FALSE}
library(leaflet)
# Define contintents and their immigrations numbers
continents <- data.frame(
  name = c("North America", "South America", "Europe", "Africa", "Asia", "Norway"),
  lat = c(41.384266, -18.261586, 48.699615, 4.617496, 32.47229, 63.425478),
  lng = c(-104.055934, -57.415058, 13.838426, 28.019693, 78.302593, 10.408549),
  immig = c(1, 3, 53, 12, 30, 0))

# Define UI functions
scaling <- function(val) {
  floor(log10(4 + val) * 40)
}


contIcon <- makeIcon(
 iconUrl = ifelse(continents$name != "Norway",
                  "https://www.wahbexchange.org/wp-content/uploads/2015/08/immigrant_customs-150x150@2x.png",
                  "https://upload.wikimedia.org/wikipedia/commons/7/70/Flag_of_Norway_with_proportions.svg"),
  iconWidth = ifelse(continents$name != "Norway", scaling(continents$immig/2), 350/10), 
  iconHeight = ifelse(continents$name != "Norway", scaling(continents$immig), 260/10),
  iconAnchorX = ifelse(continents$name != "Norway", scaling(continents$immig/4), floor(350/20)),
  iconAnchorY = ifelse(continents$name != "Norway", scaling(continents$immig/2), 260/20)
)

contPopup <- paste(continents$immig, ' %', '<br>', continents$name)

# Build the map
continents %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers(icon = contIcon, popup = contPopup)
```